# Site settings
title: Fatima Elzahra Khan
description: Final Year Chemical Engineer at Imperial College London
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Fatima Elzahra Khan
user_description: Fourth year Chemical Engineering student at <a href="https://www.imperial.ac.uk/chemical-engineering">Imperial College London</a>. <br> 2020-21 Vice-Chair of <a href="https://chemengsoc.com">Imperial College Chemical Engineering Society</a>. <br> 2019-20 President of the <a href="https://www.cgcu.net">City and Guilds College Union</a>, enhancing the student engineer experience. 

user_title: Final Year Chemical Engineer
email: fatimaelzahrakhan@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
