# Site settings
title: Fatima Elzahra Khan
description: 
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Fatima Elzahra Khan
user_description: A third year Chemical Engineering student at <a style="text-decoration:none" href="https://www.imperial.ac.uk/chemical-engineering"><b>Imperial College London</b></a>. Vice President of the <a style="text-decoration:none" href="https://www.cgcu.net"><b>City and Guilds College Union</b></a>, enhancing the student engineer experience.
user_title: Chemical Engineering Student
email: fatimaelzahrakhan@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
